import * as Yup from "yup";
import { inquiryTypes, priorities } from "../../pages/Inquary/inquiryOptions";

const getInquiryFields = (assigneeData = []) => ({
  jobNo: {
    name: "jobNo",
    type: "text",
    placeholder: "Job No",
    initialValue: "",
    // validation: Yup.string().required("Job No is required"),
  },
  jobDate: {
    name: "jobDate",
    type: "date",
    placeholder: "Job Date",
    initialValue: new Date().toISOString().split("T")[0],
    validation: Yup.string().required("Job Date is required"),
  },
  deliveredBy: {
    name: "deliveredBy",
    type: "text",
    placeholder: "Delivered By",
    initialValue: "",
    validation: Yup.string().required("Delivered By is required"),
  },
  customer: {
    name: "customer",
    type: "text",
    placeholder: "Customer",
    initialValue: "",
    validation: Yup.string().required("Customer is required"),
  },
  itemName: {
    name: "itemName",
    type: "text",
    placeholder: "Item Name",
    initialValue: "",
    validation: Yup.string().required("Item Name is required"),
  },
  serialNo: {
    name: "serialNo",
    type: "text",
    placeholder: "Serial No",
    initialValue: "",
    validation: Yup.string().required("Serial No is required"),
  },
  description: {
    name: "description",
    type: "textarea",
    placeholder: "Nature Of Faulty",
    initialValue: "",
    validation: Yup.string().required("Nature Of Faulty is required"),
  },
  toDo: {
    name: "toDo",
    type: "textarea",
    placeholder: "To Do",
    initialValue: "",
    validation: Yup.string().required("To Do is required"),
  },
  charger: {
    name: "charger",
    type: "checkbox",
    initialValue: false,
    validation: Yup.boolean(),
    placeholder: "Charger",
  },
  powerCable: {
    name: "powerCable",
    type: "checkbox",
    initialValue: false,
    validation: Yup.boolean(),
    placeholder: "Power Cable",
  },
  bag: {
    name: "bag",
    type: "checkbox",
    initialValue: false,
    validation: Yup.boolean(),
    placeholder: "Bag",
  },
  toner: {
    name: "toner",
    type: "checkbox",
    initialValue: false,
    validation: Yup.boolean(),
    placeholder: "Toner",
  },
  cartridge: {
    name: "cartridge",
    type: "checkbox",
    initialValue: false,
    validation: Yup.boolean(),
    placeholder: "Cartridge",
  },
  ribbon: {
    name: "ribbon",
    type: "checkbox",
    initialValue: false,
    validation: Yup.boolean(),
    placeholder: "Ribbon",
  },
  mouse: {
    name: "mouse",
    type: "checkbox",
    initialValue: false,
    validation: Yup.boolean(),
    placeholder: "Mouse",
  },
  usbcable: {
    name: "usbcable",
    type: "checkbox",
    initialValue: false,
    validation: Yup.boolean(),
    placeholder: "USB Cable",
  },
  videoCable: {
    name: "videoCable",
    type: "checkbox",
    initialValue: false,
    validation: Yup.boolean(),
    placeholder: "Video Cable",
  },
  serviceType: {
    name: "serviceType",
    type: "select",
    placeholder: "Service Type",
    dataBinding: { data: inquiryTypes, keyField: "key", valueField: "value" },
    initialValue: inquiryTypes[0].key,
    validation: Yup.string(),
  },
  priority: {
    name: "priority",
    type: "select",
    placeholder: "Priority",
    dataBinding: { data: priorities, keyField: "key", valueField: "value" },
    initialValue: priorities[1].key,
    validation: Yup.string(),
  },
  assignee: {
    name: "assignee",
    type: "select",
    placeholder: "Assignee",
    dataBinding: {
      data: assigneeData, keyField: "id", valueField: "partnerName",
    },
    initialValue: assigneeData[0]?.id,
    validation: Yup.string(),
  },
  dueDate: {
    name: "dueDate",
    type: "date",
    placeholder: "Due Date",
    initialValue: new Date().toISOString().split("T")[0],
    validation: Yup.string().required("Due Date is required"),
  },
});

export default getInquiryFields;
